stages:
- stage: 'BlackDuck_Scan'
  jobs:
    - job: detect
      steps:
      - task: CmdLine@2
        displayName: 'Install Python dependencies'
        inputs:
          script: |
            find . -name "requirements.txt" -type f -exec sh -c '
              for req in "$@"; do
                  while IFS= read -r package || [ -n "$package" ]; do
                      pip install --no-cache-dir --no-clean --no-deps "$package" || echo "Failed to install $package"
                  done < "$req"
              done
            ' sh {} +

      - task: SynopsysDetectTask@9
        displayName: 'Run Synopsys Detect'
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=GL_Advisor
            --detect.project.version.name=2.0
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
            --detect.code.location.name=python-dependencies-GL_Advisor-2.0
          DetectVersion: 'latest'

